project_id = "qqxhkaowexieednyazwq"

[functions.create-user]
verify_jwt = true

[functions.update-user]
verify_jwt = true

[functions.extract-yacht-specs]
verify_jwt = true

[functions.import-memorial-okean]
verify_jwt = false
