project_id = "qqxhkaowexieednyazwq"

[functions.create-user]
verify_jwt = true

[functions.update-user]
verify_jwt = true

[functions.extract-yacht-specs]
verify_jwt = true

[functions.create-fy850-options]
verify_jwt = true

[functions.send-quotation-email]
verify_jwt = true

[functions.generate-quotation-pdf]
verify_jwt = true

[functions.check-expiring-quotations]
verify_jwt = false

[functions.create-contract-from-quotation]
verify_jwt = true

