project_id = "qqxhkaowexieednyazwq"

[functions.create-user]
verify_jwt = true

[functions.update-user]
verify_jwt = true

[functions.extract-yacht-specs]
verify_jwt = true

[functions.create-fy850-options]
verify_jwt = true

[functions.send-quotation-email]
verify_jwt = true

[functions.generate-quotation-pdf]
verify_jwt = true

[functions.check-expiring-quotations]
verify_jwt = false

[functions.send-contract-email]
verify_jwt = true

[functions.generate-contract-pdf]
verify_jwt = true

[functions.generate-original-contract-pdf]
verify_jwt = true

[functions.generate-ato-pdf]
verify_jwt = true

[functions.convert-customization-to-ato]
verify_jwt = true

[functions.create-contract-from-quotation]
verify_jwt = true

[functions.advance-customization-workflow]
verify_jwt = true

[functions.advance-ato-workflow]
verify_jwt = true

[functions.enrich-item-with-ai]
verify_jwt = true

[functions.search-product-images]
verify_jwt = true

[functions.extract-from-url]
verify_jwt = true

[functions.generate-contract-summary-pdf]
verify_jwt = true

[functions.reset-user-mfa]
verify_jwt = true
